version: "3.8"

services:
  node_db:
    image: mysql:5.7
    env_file:
      - ./.env
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:4000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
