version: "3.8"

services:
  node_db:
    image: mysql:5.7
    env_file:
      - ./.env
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql